package com.example.chasem.sportstracker;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import org.w3c.dom.Text;

public class TeamStats extends AppCompatActivity
{
    TextView playerone;
    TextView p_average;

    TextView at_bats;
    TextView at_bats2;
    TextView at_bats3;
    TextView at_bats4;
    TextView at_bats5;
    TextView at_bats6;
    TextView at_bats7;
    TextView at_bats8;
    TextView at_bats9;
    TextView hitamount;
    TextView hitamount1;
    TextView hitamount2;
    TextView hitamount3;
    TextView hitamount4;
    TextView hitamount5;
    TextView hitamount6;
    TextView hitamount7;
    TextView hitamount8;
    TextView homerun_amount;
    TextView homerun1_amount;
    TextView homerun2_amount;
    TextView homerun3_amount;
    TextView homerun4_amount;
    TextView homerun5_amount;
    TextView homerun6_amount;
    TextView homerun7_amount;
    TextView homerun8_amount;
    TextView strikeout_amount;
    TextView strikeouttwo;
    TextView strikeoutthree;
    TextView strikeoutfour;
    TextView strikeoutfive;
    TextView strikeoutsix;
    TextView strikeoutseven;
    TextView strikeouteight;
    TextView strikeoutnine;
    TextView playertwo;
    TextView playertwoaverage;
    TextView playerthree;
    TextView playerthreeaverage;
    TextView playerfour;
    TextView playerfouraverage;
    TextView playerfive;
    TextView playerfiveaverage;
    TextView playersix;
    TextView playersixaverage;
    TextView playersevem;
    TextView playersevenaverage;
    TextView playereight;
    TextView playereightaverage;
    TextView playernine;
    TextView playernineaverage;
    Button clear22;
int counter2=1;



        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_stats);
            playerone = (TextView)findViewById(R.id.Player1);
            at_bats = (TextView)findViewById(R.id.atBat_amount);
            at_bats2=(TextView)findViewById(R.id.atbat2);
            at_bats3=(TextView)findViewById(R.id.atbat3);
            at_bats4=(TextView)findViewById(R.id.atbat4);
            at_bats5=(TextView)findViewById(R.id.atbat5);
            at_bats6=(TextView)findViewById(R.id.atbat6);
            at_bats7=(TextView)findViewById(R.id.atbat7);
            at_bats8=(TextView)findViewById(R.id.atbat8);
            at_bats9=(TextView)findViewById(R.id.atbat9);
            hitamount = (TextView)findViewById(R.id.hit_amount);
            hitamount1=(TextView)findViewById(R.id.hitstwo);
            hitamount2=(TextView)findViewById(R.id.hitsthree);
            hitamount3=(TextView)findViewById(R.id.hitsfour);
            hitamount4=(TextView)findViewById(R.id.hitsfive);
            hitamount5=(TextView)findViewById(R.id.hitssix);
            hitamount6=(TextView)findViewById(R.id.hitsseven);
            hitamount7=(TextView)findViewById(R.id.hitseight);
            hitamount8=(TextView)findViewById(R.id.hitsnine);
            homerun_amount = (TextView)findViewById(R.id.hr_amount);
            homerun1_amount=(TextView)findViewById(R.id.hr1_amount);
            homerun2_amount=(TextView)findViewById(R.id.hr2_amount);
            homerun3_amount=(TextView)findViewById(R.id.hr3_amount);
            homerun4_amount=(TextView)findViewById(R.id.hr4_amount);
            homerun5_amount=(TextView)findViewById(R.id.hr5_amount);
            homerun6_amount=(TextView)findViewById(R.id.hr6_amount);
            homerun7_amount=(TextView)findViewById(R.id.hr7_amount);
            homerun8_amount=(TextView)findViewById(R.id.hr8_amount);
            strikeout_amount = (TextView)findViewById(R.id.k_amount);
            strikeouttwo=(TextView)findViewById(R.id.strikeout2);
            strikeoutthree=(TextView)findViewById(R.id.strikeout3);
            strikeoutfour=(TextView)findViewById(R.id.strikeout4);
            strikeoutfive=(TextView)findViewById(R.id.strikeout5);
            strikeoutsix=(TextView)findViewById(R.id.strikeout6);
            strikeoutseven=(TextView)findViewById(R.id.strikeout7);
            strikeouteight=(TextView)findViewById(R.id.strikeout8);
            strikeoutnine=(TextView)findViewById(R.id.strikeout9);

            playertwo = (TextView)findViewById(R.id.Player2);
            playerthree = (TextView)findViewById(R.id.Player3);
            playerfour = (TextView)findViewById(R.id.Player4);
            playerfive = (TextView)findViewById(R.id.Player5);
            playersix= (TextView)findViewById(R.id.Player6);
            playersevem = (TextView)findViewById(R.id.Player7);
            playereight= (TextView)findViewById(R.id.Player8);
            playernine= (TextView)findViewById(R.id.Player9 );
            p_average = (TextView)findViewById(R.id.PlayerAverage);
            playertwoaverage= (TextView)findViewById(R.id.player2average);
            playerthreeaverage = (TextView)findViewById(R.id.player3average);
            playerfouraverage = (TextView)findViewById(R.id.player4average);
            playerfiveaverage = (TextView)findViewById(R.id.player5average);
            playersixaverage = (TextView)findViewById(R.id.player6average);
            playersevenaverage = (TextView)findViewById(R.id.player7average);
            playereightaverage = (TextView)findViewById(R.id.player8average);
            playernineaverage = (TextView)findViewById(R.id.player9average);







            String counter = getIntent().getStringExtra(MainActivity.COUNTER);
            String gotit = getIntent().getStringExtra(MainActivity.FIRST_VALUE);
            String name1 = getIntent().getStringExtra(MainActivity.FIRST_VALUE1);
            String name2 = getIntent().getStringExtra(MainActivity.FIRST_VALUE2);
            String name3 = getIntent().getStringExtra(MainActivity.FIRST_VALUE3);
            String name4 = getIntent().getStringExtra(MainActivity.FIRST_VALUE4);
            String name5 = getIntent().getStringExtra(MainActivity.FIRST_VALUE5);
            String name6 = getIntent().getStringExtra(MainActivity.FIRST_VALUE6);
            String name7 = getIntent().getStringExtra(MainActivity.FIRST_VALUE7);
            String name8 = getIntent().getStringExtra(MainActivity.FIRST_VALUE8);
            String gotit2 = getIntent().getStringExtra(MainActivity.SECOND_VALUE);
            String gotit22 = getIntent().getStringExtra(MainActivity.SECOND_VALUE1);
            String gotit23 = getIntent().getStringExtra(MainActivity.SECOND_VALUE2);
            String gotit24 = getIntent().getStringExtra(MainActivity.SECOND_VALUE3);
            String gotit25 = getIntent().getStringExtra(MainActivity.SECOND_VALUE4);
            String gotit26 = getIntent().getStringExtra(MainActivity.SECOND_VALUE5);
            String gotit27 = getIntent().getStringExtra(MainActivity.SECOND_VALUE6);
            String gotit28 = getIntent().getStringExtra(MainActivity.SECOND_VALUE7);
            String gotit29 = getIntent().getStringExtra(MainActivity.SECOND_VALUE8);
            String gotit3 = getIntent().getStringExtra(MainActivity.THIRD_VALUE);
            String gotit7 = getIntent().getStringExtra(MainActivity.THIRD_VALUE2);
            String gotit8 = getIntent().getStringExtra(MainActivity.THIRD_VALUE3);
            String gotit9 = getIntent().getStringExtra(MainActivity.THIRD_VALUE4);
            String gotit10 = getIntent().getStringExtra(MainActivity.THIRD_VALUE5);
            String gotit11 = getIntent().getStringExtra(MainActivity.THIRD_VALUE6);
            String gotit12 = getIntent().getStringExtra(MainActivity.THIRD_VALUE7);
            String gotit13 = getIntent().getStringExtra(MainActivity.THIRD_VALUE8);
            String gotit14 = getIntent().getStringExtra(MainActivity.THIRD_VALUE9);
            String gotit4 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE);
            String gotit41 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE1);
            String gotit42 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE2);
            String gotit43 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE3);
            String gotit44 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE4);
            String gotit45 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE5);
            String gotit46 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE6);
            String gotit47 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE7);
            String gotit48 = getIntent().getStringExtra(MainActivity.FOURTH_VALUE8);
            String gotit5 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE);
            String gotit51 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE1);
            String gotit52 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE2);
            String gotit53 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE3);
            String gotit54 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE4);
            String gotit55 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE5);
            String gotit56 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE6);
            String gotit57 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE7);
            String gotit58 = getIntent().getStringExtra(MainActivity.FIFTH_VALUE8);
            String gotit6 = getIntent().getStringExtra(MainActivity.SIX_VALUE);
            String gotit61 = getIntent().getStringExtra(MainActivity.SIX_VALUE1);
            String gotit62 = getIntent().getStringExtra(MainActivity.SIX_VALUE2);
            String gotit63 = getIntent().getStringExtra(MainActivity.SIX_VALUE3);
            String gotit64 = getIntent().getStringExtra(MainActivity.SIX_VALUE4);
            String gotit65 = getIntent().getStringExtra(MainActivity.SIX_VALUE5);
            String gotit66 = getIntent().getStringExtra(MainActivity.SIX_VALUE6);
            String gotit67 = getIntent().getStringExtra(MainActivity.SIX_VALUE7);
            String gotit68 = getIntent().getStringExtra(MainActivity.SIX_VALUE8);






            if(counter.equals("1"))
            {
                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);

            }
            if(counter.equals("2")){

                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);

            }
            if(counter.equals("3")){
                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);

            }
            if(counter.equals("4")){
                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);

            }
            if(counter.equals("5")){
                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);

            }
            if(counter.equals("6")){
                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);


            }
            if(counter.equals("7")){
                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);


            }

            if(counter.equals("8")){
                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);


            }

            if(counter.equals("9")){
                playerone.setText(gotit);
                p_average.setText(gotit2);
                playertwoaverage.setText(gotit22);
                playerthreeaverage.setText(gotit23);
                playerfouraverage.setText(gotit24);
                playerfiveaverage.setText(gotit25);
                playersixaverage.setText(gotit26);
                playersevenaverage.setText(gotit27);
                playereightaverage.setText(gotit28);
                playernineaverage.setText(gotit29);
                at_bats.setText(gotit3);
                at_bats2.setText(gotit7);
                at_bats3.setText(gotit8);
                at_bats4.setText(gotit9);
                at_bats5.setText(gotit10);
                at_bats6.setText(gotit11);
                at_bats7.setText(gotit12);
                at_bats8.setText(gotit13);
                at_bats9.setText(gotit14);
                hitamount.setText(gotit4);
                hitamount1.setText(gotit41);
                hitamount2.setText(gotit42);
                hitamount3.setText(gotit43);
                hitamount4.setText(gotit44);
                hitamount5.setText(gotit45);
                hitamount6.setText(gotit46);
                hitamount7.setText(gotit47);
                hitamount8.setText(gotit48);
                homerun_amount.setText(gotit5);
                homerun1_amount.setText(gotit51);
                homerun2_amount.setText(gotit52);
                homerun3_amount.setText(gotit53);
                homerun4_amount.setText(gotit54);
                homerun5_amount.setText(gotit55);
                homerun6_amount.setText(gotit56);
                homerun7_amount.setText(gotit57);
                homerun8_amount.setText(gotit58);
                strikeout_amount.setText(gotit6);
                strikeouttwo.setText(gotit61);
                strikeoutthree.setText(gotit62);
                strikeoutfour.setText(gotit63);
                strikeoutfive.setText(gotit64);
                strikeoutsix.setText(gotit65);
                strikeoutseven.setText(gotit66);
                strikeouteight.setText(gotit67);
                strikeoutnine.setText(gotit68);
                playertwo.setText(name1);
                playerthree.setText(name2);
                playerfour.setText(name3);
                playerfive.setText(name4);
                playersix.setText(name5);
                playersevem.setText(name6);
                playereight.setText(name7);
                playernine.setText(name8);


            }

        }

}
